### ISSUE TITLE
Move repo to new organisation owner

### ISSUE THREAD

**Issue by MilesMcBain** [cranchange/cran_change.org#10]
It's way better than the letter I would have written so I think it deserves it's own home.

**Comment by MilesMcBain** [comment]
Okay we are live at https://github.com/cranchange/cran_change.org

Let me know if you want org invites @jonocarroll @adamhsparks @llrs @wlandau, I don't mind if you'd prefer not to.

**Comment by wlandau** [comment]
Sure Miles, that would be great.

**Comment by llrs** [comment]
I won't need org permissions, with just PR and issues is enough to contribute to the letter. But maybe this org could be also home for https://github.com/llrs/cran_histories

**Comment by MilesMcBain** [comment]
Yes I think that's a really great idea to collect context with the action!

**Comment by MilesMcBain** [comment]
I've also set up the org so it can accept members with limited permissions. I was thinking of making a logo and that way it could be a badge people could display in their GitHub profile if that appeals to them.

**Comment by llrs** [comment]
To [transfer the repository](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository) I'll need "permission to create a repository in the target organization." If you add me to the org I think it would be enough to allow me to transfer it.

**Comment by MilesMcBain** [comment]
You're invited @llrs!

**Comment by adamhsparks** [comment]
Sure, flick an invite my way, please.

**Comment by MilesMcBain** [comment]
@adamhsparks you're invited

**Comment by pat-s** [comment]
Happy to support this initiative in any possible way!
