### ISSUE TITLE
soften intro

### ISSUE THREAD

**Issue by MilesMcBain** [cranchange/cran_change.org#11]
I've had feedback volunteered via a number of channels and by far the most common item seems to be that it would be good to ease into things and pay respects to CRAN up front.

I have some ideas on how to do this.

**Comment by MilesMcBain** [comment]
Okay a fairy big rejig in: 253dc29

**Comment by llrs** [comment]
> This letter seeks to draw attention to deficiencies in empathy and fairness that are impacting the R community.
> 
> So in the spirit of empathy and fairness we begin by acknowledging the sustained dedication of our CRAN administrators, and thank them for the foundational piece of infrastructure they have built which has made the way we work together with R possible.
> 
> There is no question that holding an ever increasing pool of software and contributors to high standards, and continuously validating those standards are held is a resource intensive technical feat from which great public good has been derived.
> 
> Yet is also with empathy for the experiences of CRAN's users, and in fairness to the future R community that we, the undersigned R community members, find ourselves with no other reasonable alternative than to unify our voices in protest against actions that are damaging the R package ecosystem.
> 
> A pattern of increasingly inconsistent and heavy-handed behaviour by CRAN administrators has shaken our trust that our community's central package archive is being managed sustainably.

**Comment by llrs** [comment]
I agree it the header was quite combative. I reorganized a bit the header and pointed out  a sentence that put me off on #12. (Sorry, closing was a missclick)

**Comment by MilesMcBain** [comment]
Thankyou!

Ok that sentence to something like:

> find ourselves with no other reasonable alternative than to unify our voices in a call to reform CRAN practices that are damaging the R package ecosystem.

?

**Comment by llrs** [comment]
Yes, I like it more. I added it to the PR

**Comment by MilesMcBain** [comment]
I'll close this in favour of the PR then :+1:
