### ISSUE TITLE
Getting feedback from broader community

### ISSUE THREAD

**Issue by MilesMcBain** [cranchange/cran_change.org#13]
I think some changes may still be made, but the substantive elements of the letter: the harmful practices and our reforms probably won't change too much unless we get some input from the wider community.

I was thinking it might be worth inviting feedback from the R community somehow.

It could be done by raising it directly with community groups e.g RLadies, or a more general call out on Twitter or something.

The prompt could be something like: If you or someone you know has had an experience with CRAN that didn't meet your expectations of how CRAN should work, do you find that experience represented in the letter? Would the proposed reforms have prevented it?

Thoughts @cranchange/authors ?

**Comment by llrs** [comment]
Feedback from more people would be interesting, but I wouldn't announce publicly yet (Twitter), I would start by sharing the letter with communities on their slack of rOpenSci, Rladies, Bioconductor, R working group, WhyR... . If the message reaches CRAN members before the letter is finished writing this could cause some misunderstanding, specially if the tone or some other points change.

**Comment by MilesMcBain** [comment]
I knocked up this form to capture the feedback: https://forms.gle/iS5UFnv3yTtW6Dzg9

**Comment by MilesMcBain** [comment]
I have closed the form submission after 2 weeks.
