### ISSUE TITLE
Refocus, point 6 about resubmissions. 

### ISSUE THREAD

**Issue by llrs** [cranchange/cran_change.org#24]
About point 6 "Publish a policy on re-submission intervals that can be consistently applied", [CRAN policy](https://cran.r-project.org/web/packages/policies.html) says this:

> Submitting updates should be done responsibly and with respect for the volunteers’ time. Once a package is established (which may take several rounds), “no more than every 1–2 months” seems appropriate

This seems only a problem if package maintainer gets requests to modify package because some issues on CRAN (or dependencies) and later on wants to update the package. There seems to be already automatic checks on place (on the winbuilder at least, see this [data point on twitter](https://twitter.com/wmlandau/status/1398399339244961797)). 

Perhaps it should be reworded to clarify better how to reconcile both CRAN policies to update packages according to policies and dependencies changes **and** the maintainer being able to update the package in a timely fashion.

**Comment by MilesMcBain** [comment]
This is a good point but it becomes less of an issue in the context of other reforms?

E.g. longer archival time frames, more visibility of upcoming CRAN policy changes, reproducible CRAN environments.

**Comment by llrs** [comment]
Not really. If resubmissions are so important that have their own bullet on the petitions it should be really well framed. Otherwise CRAN could point to the policy and say: "you haven't read it carefully".

**Comment by MilesMcBain** [comment]
I guess an obvious answer is that if CRAN demand you update then you get 1 update added to your quota. But I was trying to give examples only rather than specific implementations.

**Comment by MilesMcBain** [comment]
But it might be good to mention this as a source of confusion. 👍

**Comment by MilesMcBain** [comment]
I've added some text to address this.
