### ISSUE TITLE
Strengthen the third sentence

### ISSUE THREAD

**Issue by wlandau** [cranchange/cran_change.org#4]
> If left unchecked we believe this pattern will undermine CRAN's position as a comprehensive archive of quality software, since is it already leading many to question whether submitting to CRAN is worthwhile, and wonder if tests deployed on CRAN are truly assets or liabilities.

We might be able to allude more directly to actual instances of suppressing tests, e.g. https://twitter.com/wmlandau/status/1386333190315511808/retweets/with_comments.

> We have observed that in response to this pattern, many contributors feel compelled to suppress the majority of their tests and examples, which degrades the reverse dependency check system. And many contributors are seeking alternatives to CRAN.

**Comment by MilesMcBain** [comment]
Not sure about this one for this sentence. I made the change, but then it felt a bit too specific to the testing issue which is only part of the story.

**Comment by wlandau** [comment]
Good point, my original suggestion was probably too narrow and too specific. I think we can still keep things general while asserting that we have already observed degradation.

**Comment by MilesMcBain** [comment]
What about the above commit @wlandau it asserts the degradation is happening because we are doing it. I know I have used `skip_on_cran()` liberally.

**Comment by llrs** [comment]
Beyond skip_on_cran(), moving vignettes to articles or books outside CRAN to avoid being checked on CRAN or Bioconductor (or this letter itself) also reflects this degradation. I like the new wording.

**Comment by wlandau** [comment]
I do too, thanks Miles.
