### ISSUE TITLE
Briefly elaborate on the ways that sudden archivals take place

### ISSUE THREAD

**Issue by wlandau** [cranchange/cran_change.org#5]
> Archiving packages with little or no warning discriminates against contributors with less time available on short notice.

Some readers might claim that CRAN administrators actually do give advance notice, e.g. "please correct before 2021-04-10 to safely retain your package on CRAN". We might want to clarify that when an issue is resolved, the grace period does not necessarily renew, as was the case with me. (Not actually sure if that's too much of a rabbit hole.)

**Comment by llrs** [comment]
There were some instances were this was not the case. The package was removed right after an email from CRAN

**Comment by wlandau** [comment]
Thanks @llrs, I was unaware. In that case, I am less sure this letter is the right place to elaborate on the specifics of how packages get unfairly archived.

**Comment by llrs** [comment]
CRAN policy preamble explicitly says that they are allowed to do so, as I recently discovered https://github.com/llrs/cran_histories/issues/16
