### ISSUE TITLE
Point 2 mentioing current shared build environments and configuration

### ISSUE THREAD

**Issue by llrs** [cranchange/cran_change.org#9]
I think the letter could mention and build upon the existing summary page:
https://cran.r-project.org/web/checks/check_flavors.html

> 2. Standardise build environments and publish configuration so that contributors can test against CRAN environments, e.g. via RHub

to 

> 2. Add all the details of build environments and configuration shared on https://cran.r-project.org/web/checks/check_flavors.html so that contributors can test against CRAN environments, e.g. via RHub.

**Comment by wlandau** [comment]
I think it is worth emphasizing that we are requesting complete/reproducible build specs (all the details, not just some) to prevent surprises.

**Comment by MilesMcBain** [comment]
Yeah that's what that point is intended to capture @wlandau I'll tweak so that's clear.

@llrs I don't see the URL of the configuration being that *important, depending on the format of the reproducible config it may make more sense to publish it in a repository.

**Comment by llrs** [comment]
I didn't meant that the url was important but point that they have done some effort but currently it is not enough and encourage them to continue with these efforts (filling up the configuration for all the flavors, adding more details or the actual files used...)

**Comment by MilesMcBain** [comment]
Ah okay thanks for clarifying 👍

I guess I was hoping "standardise" could include "rationalise"... Looking at you Solaris
